# Generated by Django 4.1 on 2023-01-09 23:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ColaModel',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_de_la_cola', models.CharField(max_length=200)),
                ('creada_por', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('usuarios_acceso', models.ManyToManyField(related_name='Usuarios_con_acceso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cola',
                'verbose_name_plural': 'Colas',
            },
        ),
    ]
